# coding: utf-8
# review/compare_v1_v2.py
# Compare RF and SVM v1 vs v2 results (deterministic sampling impact).
#
# Reads:
#   results/RF/rf_v1_results.csv
#   results/RF_v2/rf_v2_results.csv
#   results/SVM/svm_v1_results.csv
#   results/SVM_v2/svm_v2_results.csv
#
# Outputs:
#   review/v1_vs_v2_comparison.csv
#   review/v1_vs_v2_comparison.md

import csv
import math
from collections import defaultdict
from pathlib import Path

METRICS = ['accuracy', 'sensitivity', 'specificity', 'f1', 'auc']

SOURCES = [
    ('RF',  Path('results/RF/rf_v1_results.csv'),       Path('results/RF_v2/rf_v2_results.csv')),
    ('SVM', Path('results/SVM/svm_v1_results.csv'),     Path('results/SVM_v2/svm_v2_results.csv')),
]

REVIEW_DIR = Path('review')
REVIEW_DIR.mkdir(exist_ok=True)
OUT_CSV = REVIEW_DIR / 'v1_vs_v2_comparison.csv'
OUT_MD  = REVIEW_DIR / 'v1_vs_v2_comparison.md'


def load_results(path):
    """Return dict[(method, n_bands)] -> {metric: [values]}."""
    if not path.exists():
        print('  [missing] {}'.format(path))
        return {}
    data = defaultdict(lambda: {m: [] for m in METRICS})
    with open(path, newline='') as fh:
        for row in csv.DictReader(fh):
            key = (row['method'], row['n_bands'])
            for m in METRICS:
                v = row.get(m, '')
                if v and v != 'nan':
                    try:
                        data[key][m].append(float(v))
                    except ValueError:
                        pass
    return data


def mean_std(vals):
    if not vals:
        return float('nan'), float('nan')
    n = len(vals)
    mu = sum(vals) / n
    var = sum((x - mu) ** 2 for x in vals) / n
    return mu, math.sqrt(var)


rows_out = []

for model, v1_path, v2_path in SOURCES:
    print('Loading {} ...'.format(model))
    v1 = load_results(v1_path)
    v2 = load_results(v2_path)

    if not v1:
        print('  v1 missing — skipping {}'.format(model))
        continue
    if not v2:
        print('  v2 missing — skipping {} (run the sweep first)'.format(model))
        continue

    all_keys = sorted(set(v1.keys()) | set(v2.keys()))
    for (method, n_bands) in all_keys:
        for metric in METRICS:
            v1_vals = v1.get((method, n_bands), {}).get(metric, [])
            v2_vals = v2.get((method, n_bands), {}).get(metric, [])
            v1_mu, v1_sd = mean_std(v1_vals)
            v2_mu, v2_sd = mean_std(v2_vals)
            d_mean = v2_mu - v1_mu
            std_ratio = (v2_sd / v1_sd) if v1_sd > 1e-9 else float('nan')

            # Flags
            flags = []
            if abs(d_mean) > 0.02:
                flags.append('SHIFT')
            if not math.isnan(std_ratio) and std_ratio < 0.70:
                flags.append('VARIANCE_DROP')
            flag_str = ','.join(flags)

            rows_out.append({
                'model':      model,
                'method':     method,
                'n_bands':    n_bands,
                'metric':     metric,
                'v1_mean':    '{:.4f}'.format(v1_mu),
                'v1_std':     '{:.4f}'.format(v1_sd),
                'v2_mean':    '{:.4f}'.format(v2_mu),
                'v2_std':     '{:.4f}'.format(v2_sd),
                'd_mean':     '{:+.4f}'.format(d_mean),
                'std_ratio':  '{:.3f}'.format(std_ratio) if not math.isnan(std_ratio) else 'nan',
                'flags':      flag_str,
            })

# ── Write CSV ──────────────────────────────────────────────────
COLS = ['model', 'method', 'n_bands', 'metric',
        'v1_mean', 'v1_std', 'v2_mean', 'v2_std',
        'd_mean', 'std_ratio', 'flags']

with open(OUT_CSV, 'w', newline='') as fh:
    writer = csv.DictWriter(fh, fieldnames=COLS)
    writer.writeheader()
    writer.writerows(rows_out)
print('Written: {}'.format(OUT_CSV))

# ── Write Markdown ─────────────────────────────────────────────
lines = [
    '# v1 vs v2 Comparison',
    '',
    'Generated by `review/compare_v1_v2.py`.',
    '',
    '**Flag legend:**',
    '- `SHIFT` — |d mean| > 0.02 (mean moved more than expected)',
    '- `VARIANCE_DROP` — std_ratio < 0.70 (good: deterministic sampling reduced variance >30%)',
    '',
    '## AUC summary (per model × combo)',
    '',
]

# AUC-only summary table
auc_rows = [r for r in rows_out if r['metric'] == 'auc']
lines.append('| model | method | n_bands | v1 AUC | v2 AUC | d mean | std_ratio | flags |')
lines.append('|---|---|---|---|---|---|---|---|')
for r in auc_rows:
    flag_cell = '⚠ ' + r['flags'] if r['flags'] else ''
    lines.append('| {model} | {method} | {n_bands} | {v1_mean}±{v1_std} | {v2_mean}±{v2_std} | {d_mean} | {std_ratio} | {flag} |'.format(
        flag=flag_cell, **r))

lines += [
    '',
    '## Full metric table',
    '',
    '| model | method | n_bands | metric | v1 mean±std | v2 mean±std | d mean | std_ratio | flags |',
    '|---|---|---|---|---|---|---|---|---|',
]
for r in rows_out:
    flag_cell = '⚠ ' + r['flags'] if r['flags'] else ''
    lines.append('| {model} | {method} | {n_bands} | {metric} | {v1_mean}±{v1_std} | {v2_mean}±{v2_std} | {d_mean} | {std_ratio} | {flag} |'.format(
        flag=flag_cell, **r))

lines.append('')

with open(OUT_MD, 'w', encoding='utf-8') as fh:
    fh.write('\n'.join(lines) + '\n')
print('Written: {}'.format(OUT_MD))

# ── Console summary ────────────────────────────────────────────
shift_rows = [r for r in rows_out if 'SHIFT' in r['flags']]
vdrop_rows = [r for r in rows_out if 'VARIANCE_DROP' in r['flags']]
print()
print('Total combos compared: {}'.format(len(set((r['model'], r['method'], r['n_bands']) for r in rows_out))))
print('SHIFT flags (|d_mean| > 0.02): {}'.format(len(shift_rows)))
for r in shift_rows:
    print('  {} {}/{} {} : d={}'.format(r['model'], r['method'], r['n_bands'], r['metric'], r['d_mean']))
print('VARIANCE_DROP flags (std_ratio < 0.70): {}'.format(len(vdrop_rows)))
for r in vdrop_rows:
    print('  {} {}/{} {} : std_ratio={}'.format(r['model'], r['method'], r['n_bands'], r['metric'], r['std_ratio']))
