import json

nb = json.load(open('4d_vit.ipynb', encoding='utf-8'))
cells = nb['cells']
idx = {c['id']: i for i, c in enumerate(cells)}

# ── 1. Insert pro-plus-setup after mount-drive ───────────────
pro_setup = {
    'cell_type': 'code',
    'id': 'pro-plus-setup',
    'metadata': {},
    'execution_count': None,
    'outputs': [],
    'source': (
        '# ============================================================\n'
        '# COLAB PRO+ SETUP  (Northeastern -- A100 + High-RAM)\n'
        '# ============================================================\n'
        '# ViT is memory-heavy. If you hit OOM:\n'
        '#   Runtime > Change runtime type > toggle High-RAM on\n'
        'import torch\n'
        'if torch.cuda.is_available():\n'
        '    print("GPU :", torch.cuda.get_device_name(0))\n'
        '    print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1e9, 1), "GB")\n'
        'else:\n'
        '    print("WARNING: No GPU found -- check Runtime > Change runtime type > A100")\n'
        '\n'
        'from IPython.display import display, Javascript\n'
        'display(Javascript(\'\'\'\n'
        '  setInterval(function() {\n'
        '    var btn = document.querySelector("colab-toolbar-button#connect");\n'
        '    if (btn) btn.click();\n'
        '    console.log("Keepalive " + new Date().toLocaleTimeString());\n'
        '  }, 30000);\n'
        '  console.log("Keepalive started.");\n'
        '\'\'\'))\n'
        'print("Keepalive active (30s interval).")\n'
        'print()\n'
        'print("To run without browser (close lid):")\n'
        'print("  1. Start the training loop cell first")\n'
        'print("  2. Run the [background-exec] cell below right before closing")\n'
    )
}

background_exec = {
    'cell_type': 'code',
    'id': 'background-exec',
    'metadata': {},
    'execution_count': None,
    'outputs': [],
    'source': (
        '# ============================================================\n'
        '# BACKGROUND EXECUTION  (Colab Pro+)\n'
        '# ============================================================\n'
        '# Run this cell RIGHT BEFORE closing your browser or laptop lid.\n'
        '# The A100 keeps executing -- no browser needed.\n'
        '# When back: Runtime > Reconnect to existing runtime.\n'
        '#\n'
        '# IMPORTANT: Only run this AFTER the training loop cell has started.\n'
        '# ============================================================\n'
        'from google.colab import runtime\n'
        'print("Detaching browser from runtime...")\n'
        'print("Training continues on A100 in the background.")\n'
        'print("Return and go to Runtime > Reconnect.")\n'
        'runtime.unassign()\n'
    )
}

mount_idx = idx['mount-drive']
cells.insert(mount_idx + 1, background_exec)
cells.insert(mount_idx + 1, pro_setup)

# ── 2. Update utilities — add log_progress ───────────────────
util_idx = next(i for i, c in enumerate(cells) if c['id'] == 'utilities')
cells[util_idx]['source'] = (
    '# ============================================================\n'
    '# UTILITY FUNCTIONS\n'
    '# ============================================================\n'
    '\n'
    'def is_done(csv_path, model, method, n_bands, patch_size, token_size, fold):\n'
    '    """Return True if this run row already exists in the CSV."""\n'
    '    csv_path = Path(csv_path)\n'
    '    if not csv_path.exists():\n'
    '        return False\n'
    '    with open(csv_path, "r", newline="") as fh:\n'
    '        for row in csv.DictReader(fh):\n'
    '            if (row.get("model")      == str(model)      and\n'
    '                row.get("method")     == str(method)     and\n'
    '                row.get("n_bands")    == str(n_bands)    and\n'
    '                row.get("patch_size") == str(patch_size) and\n'
    '                row.get("token_size") == str(token_size) and\n'
    '                row.get("fold")       == str(fold)):\n'
    '                return True\n'
    '    return False\n'
    '\n'
    '\n'
    'def append_row(csv_path, row, cols):\n'
    '    """Append one row to CSV, writing header if file is new."""\n'
    '    csv_path = Path(csv_path)\n'
    '    write_hdr = not csv_path.exists()\n'
    '    with open(csv_path, "a", newline="") as fh:\n'
    '        writer = csv.DictWriter(fh, fieldnames=cols, extrasaction="ignore")\n'
    '        if write_hdr:\n'
    '            writer.writeheader()\n'
    '        writer.writerow(row)\n'
    '\n'
    '\n'
    'def generate_summary(results_csv, summary_csv, cols, metric_cols):\n'
    '    """Write mean+-std summary grouped by (method, n_bands, patch_size, token_size)."""\n'
    '    from collections import defaultdict\n'
    '    data = defaultdict(lambda: {m: [] for m in metric_cols})\n'
    '    with open(results_csv, "r", newline="") as fh:\n'
    '        for row in csv.DictReader(fh):\n'
    '            key = (row["method"], row["n_bands"],\n'
    '                   row.get("patch_size", "11"), row.get("token_size", "4"))\n'
    '            for m in metric_cols:\n'
    '                if m in row and row[m] != "":\n'
    '                    data[key][m].append(float(row[m]))\n'
    '    sum_cols = ["model", "method", "n_bands", "patch_size", "token_size",\n'
    '                "fold", "loss_fn"] + metric_cols\n'
    '    with open(summary_csv, "w", newline="") as fh:\n'
    '        writer = csv.DictWriter(fh, fieldnames=sum_cols)\n'
    '        writer.writeheader()\n'
    '        for (method, n_bands, patch_size, token_size), metrics in sorted(data.items()):\n'
    '            row = {"model": MODEL, "method": method, "n_bands": n_bands,\n'
    '                   "patch_size": patch_size, "token_size": token_size,\n'
    '                   "fold": "summary", "loss_fn": LOSS_FN}\n'
    '            for m, vals in metrics.items():\n'
    '                arr = np.array(vals)\n'
    '                row[m] = "{:.4f}+-{:.4f}".format(arr.mean(), arr.std()) if len(arr) else ""\n'
    '            writer.writerow(row)\n'
    '    print("Summary ->", summary_csv)\n'
    '\n'
    '\n'
    'def save_learning_curve(train_losses, val_losses, title, save_path):\n'
    '    """Save train/val loss curve to PNG."""\n'
    '    fig, ax = plt.subplots(figsize=(7, 4))\n'
    '    ax.plot(train_losses, label="Train loss")\n'
    '    ax.plot(val_losses,   label="Val loss")\n'
    '    ax.set_xlabel("Epoch")\n'
    '    ax.set_ylabel("Loss")\n'
    '    ax.set_title(title)\n'
    '    ax.legend()\n'
    '    ax.grid(True, alpha=0.3)\n'
    '    fig.tight_layout()\n'
    '    fig.savefig(save_path, dpi=100)\n'
    '    plt.close(fig)\n'
    '\n'
    '\n'
    'def log_progress(run_num, total_runs, fold_num, method, n_bands, row=None, error=None):\n'
    '    """Append one line to progress_log.txt on Drive -- checkable from any device."""\n'
    '    import datetime\n'
    '    log_path = RESULTS_DIR / "progress_log.txt"\n'
    '    ts = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")\n'
    '    if error:\n'
    '        line = "[{}] [{:2d}/{}] fold={} {}/{} ERROR: {}\\n".format(\n'
    '            ts, run_num, total_runs, fold_num, method, n_bands, error)\n'
    '    else:\n'
    '        line = "[{}] [{:2d}/{}] fold={} {}/{} f1={:.3f} auc={:.3f} acc={:.3f} sens={:.3f} train={:.0f}s\\n".format(\n'
    '            ts, run_num, total_runs, fold_num, method, n_bands,\n'
    '            row["f1"], row["auc"], row["accuracy"], row["sensitivity"],\n'
    '            row["train_time_sec"])\n'
    '    with open(log_path, "a") as f:\n'
    '        f.write(line)\n'
    '\n'
    'print("Utilities defined.")\n'
)

# ── 3. Update main-loop — add try/except + log_progress ──────
main_idx = next(i for i, c in enumerate(cells) if c['id'] == 'main-loop')
cells[main_idx]['source'] = (
    '# ============================================================\n'
    '# MAIN TRAINING LOOP\n'
    '# 15 combos x 3 folds = 45 runs  (FullSpectrum excluded for DL)\n'
    '# ============================================================\n'
    '\n'
    'folds = get_lopocv_folds()\n'
    'grid  = get_experiment_grid()\n'
    'grid  = [(m, n) for m, n in grid if m != "FullSpectrum"]\n'
    'total_runs = len(grid) * len(folds)\n'
    'run_num    = 0\n'
    '\n'
    '_gs_main      = math.ceil(PATCH_SIZE / TOKEN_SIZE)\n'
    'N_TOKENS_MAIN = _gs_main * _gs_main\n'
    '\n'
    'print("ViT {}  |  {} combos x {} folds = {} runs".format(\n'
    '    VERSION, len(grid), len(folds), total_runs))\n'
    'print("Patch={} token_size={} n_tokens={}".format(PATCH_SIZE, TOKEN_SIZE, N_TOKENS_MAIN))\n'
    'print("Results ->", RESULTS_CSV)\n'
    'print()\n'
    '\n'
    'combo_bar = tqdm(grid, desc="Combos", unit="combo")\n'
    'for method, n_bands in combo_bar:\n'
    '    band_indices = load_band_indices(method, n_bands)\n'
    '    combo_bar.set_postfix({"method": method, "bands": n_bands})\n'
    '\n'
    '    fold_bar = tqdm(folds, desc="  Folds", unit="fold", leave=False)\n'
    '    for fold in fold_bar:\n'
    '        fold_num = fold["fold"]\n'
    '        run_num += 1\n'
    '        fold_bar.set_postfix({"fold": fold_num,\n'
    '                              "run": "{}/{}".format(run_num, total_runs)})\n'
    '\n'
    '        if is_done(RESULTS_CSV, MODEL, method, n_bands, PATCH_SIZE, TOKEN_SIZE, fold_num):\n'
    '            fold_bar.write("  [skip] {}/{} fold={}".format(method, n_bands, fold_num))\n'
    '            continue\n'
    '\n'
    '        try:\n'
    '            # ---- Load data ----\n'
    '            train_ldr, val_ldr, test_ldr, y_train = make_loaders(\n'
    '                fold, band_indices, PATCH_SIZE, TOKEN_SIZE,\n'
    '                PATCHES_PER_ROI, RANDOM_SEED, BATCH_SIZE)\n'
    '\n'
    '            n_tokens  = N_TOKENS_MAIN\n'
    '            token_dim = TOKEN_SIZE * TOKEN_SIZE * n_bands\n'
    '\n'
    '            # ---- Build model ----\n'
    '            torch.manual_seed(RANDOM_SEED)\n'
    '            model = ViT(n_tokens, token_dim, EMBED_DIM, N_HEADS, N_LAYERS,\n'
    '                        MLP_RATIO, DROPOUT).to(DEVICE)\n'
    '\n'
    '            # ---- Train ----\n'
    '            t_train = time.time()\n'
    '            train_losses, val_losses, n_epochs_run = train_fold(\n'
    '                model, train_ldr, val_ldr, y_train,\n'
    '                MAX_EPOCHS, ES_PATIENCE, LR_INIT, WARMUP_EPOCHS,\n'
    '                LR_FACTOR, LR_PATIENCE, LR_MIN, DEVICE)\n'
    '            train_time_sec = time.time() - t_train\n'
    '\n'
    '            # ---- Evaluate on test ----\n'
    '            criterion = make_criterion(y_train, DEVICE)\n'
    '            t_inf = time.time()\n'
    '            _, preds, probs, labels = evaluate_loader(model, test_ldr, criterion, DEVICE)\n'
    '            inf_ms = (time.time() - t_inf) / len(labels) * 1000\n'
    '\n'
    '            row = {\n'
    '                "model":                       MODEL,\n'
    '                "method":                      method,\n'
    '                "n_bands":                     n_bands,\n'
    '                "patch_size":                  PATCH_SIZE,\n'
    '                "token_size":                  TOKEN_SIZE,\n'
    '                "fold":                        fold_num,\n'
    '                "loss_fn":                     LOSS_FN,\n'
    '                "accuracy":                    round(accuracy_score(labels, preds), 6),\n'
    '                "sensitivity":                 round(recall_score(labels, preds, pos_label=1,\n'
    '                                                                  zero_division=0), 6),\n'
    '                "specificity":                 round(recall_score(labels, preds, pos_label=0,\n'
    '                                                                  zero_division=0), 6),\n'
    '                "f1":                          round(f1_score(labels, preds, average="macro",\n'
    '                                                              zero_division=0), 6),\n'
    '                "auc":                         round(roc_auc_score(labels, probs), 6),\n'
    '                "train_time_sec":              round(train_time_sec, 3),\n'
    '                "inference_time_per_image_ms": round(inf_ms, 6),\n'
    '            }\n'
    '\n'
    '            # ---- Save to Drive ----\n'
    '            append_row(RESULTS_CSV, row, CSV_COLS)\n'
    '\n'
    '            curve_name = "curve_{}_{}b_p{}_t{}_f{}.png".format(\n'
    '                method, n_bands, PATCH_SIZE, TOKEN_SIZE, fold_num)\n'
    '            save_learning_curve(\n'
    '                train_losses, val_losses,\n'
    '                "{} {}/{}b patch={} ts={} fold={} ({} ep)".format(\n'
    '                    MODEL, method, n_bands, PATCH_SIZE, TOKEN_SIZE, fold_num, n_epochs_run),\n'
    '                PLOTS_DIR / curve_name)\n'
    '\n'
    '            log_progress(run_num, total_runs, fold_num, method, n_bands, row=row)\n'
    '\n'
    '            fold_bar.write(\n'
    '                "  [{:2d}/{:2d}] fold={} {}/{:3d}  "\n'
    '                "acc={:.3f} sens={:.3f} spec={:.3f} f1={:.3f} auc={:.3f}  "\n'
    '                "train={:.1f}s ep={}".format(\n'
    '                    run_num, total_runs, fold_num, method, n_bands,\n'
    '                    row["accuracy"], row["sensitivity"], row["specificity"],\n'
    '                    row["f1"], row["auc"], train_time_sec, n_epochs_run))\n'
    '\n'
    '        except Exception as _e:\n'
    '            _msg = str(_e)\n'
    '            fold_bar.write("  [ERROR] fold={} {}/{} -> {}".format(\n'
    '                fold_num, method, n_bands, _msg))\n'
    '            log_progress(run_num, total_runs, fold_num, method, n_bands, error=_msg)\n'
    '\n'
    '        finally:\n'
    '            if "model" in vars():\n'
    '                del model\n'
    '            torch.cuda.empty_cache()\n'
    '\n'
    'print()\n'
    'print("All main runs complete.")\n'
)

json.dump(nb, open('4d_vit.ipynb', 'w', encoding='utf-8'), indent=1)
print('Done. Total cells:', len(nb['cells']))
